steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=europe-west4-docker.pkg.dev/$PROJECT_ID/test-tenant-1-docker/spring-boot', '.']
images: ['europe-west4-docker.pkg.dev/$PROJECT_ID/test-tenant-1-docker/spring-boot']
