steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=ieurope-west4-docker.pkg.dev/$PROJECT_ID/spring-boot', '.']
images: ['europe-west4-docker.pkg.dev/$PROJECT_ID/spring-boot']
